# Generated by Django 3.2.4 on 2021-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_usertask_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
