# Generated by Django 3.2.4 on 2021-06-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_usertask_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='end_time',
            field=models.DateTimeField(blank=True, max_length=60, null=True),
        ),
    ]
